<?php

namespace App\Database\Migrations;

use CodeIgniter\Database\Migration;

class AddAttributesToUsers extends Migration
{
    public function up()
    {
        // add additional fields to users table
        // users table is generated by shield auth migration

        $fields = [
            'full_name' => [
                'type' => 'VARCHAR',
                'constraint' => 255,
                'after' => 'username',
            ],
            'entry_year' => [
                'type' => 'YEAR',
                'after' => 'full_name',
            ],
        ];

        $this->forge->addColumn('users', $fields);
    }

    public function down()
    {
        $fields = [
            'full_name',
            'entry_year',
        ];

        $this->forge->dropColumn('users', $fields);
    }
}
